phases:
  pre_build:
    commands:
      - aws eks update-kubeconfig --region us-east-1 --name maintenance-eks

  build:
    commands:
      - kubectl apply -f namespace.yaml
      - kubectl apply -f configmap.yaml
      - kubectl apply -f secret.yaml
      - kubectl apply -f deployment.yaml
      - kubectl apply -f service.yaml
      - kubectl apply -f ingress.yaml
